name: Dependabot

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: pnpm/action-setup@master
        with:
          version: latest
      - uses: actions/checkout@master
      - run: rm -rf yarn.lock pnpm-lock.yaml package-lock.json
      - run: pnpx npm-check-updates -u
      - run: pnpm i --no-frozen-lockfile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
